### ISSUE TITLE
Doubt in Python projects

### ISSUE THREAD

**Issue by Marlysson** [iBelieve/this#10]
Do you consider that all projects made in python are made in django?

Because of line: "python manage.py .... "

**Comment by iBelieve** [comment]
No - the goal is to support all python projects, not just django/flask apps that have a `manage.py`. As you can see [here](https://github.com/iBelieve/this/blob/master/thiscli/project/python.py#L54), `manage.py` is completely optional for Python projects and only used if it is found. I'm working on supporting other formats for running projects, such as the `flask` CLI. And of course, Python projects that don't have a standardized way to run them will still support building, testing, linting, etc.

Does that answer your question? Is there a specific Python project structure you're working with that isn't working with `this`?

**Comment by Marlysson** [comment]
Wow .. For a while not.. Just know the project to contribute him.. Seems a good project.

I did think the project so much interesting.. A way to centralize the steps of development of the project .

But, do you know about "[Maven](https://maven.apache.org/)" from java platform ?

 It is responsible to create some common structures of projects ( web , cli, project, artifacts ... etc ) and too construct each step ( download libraries , as our pip together with requirements.txt , test , build's project ) do you based yourself in him ?

**Comment by iBelieve** [comment]
Yeah, I'm slightly familiar with Maven, but haven't used it, as I've always used Gradle for Android and regular Java/Kotlin projects. I'll probably add support for Maven, as I'd like to support a wide range of common build tools, but since I don't personally use it, it'll be behind tools that I do use in terms of priority. Of course, though, anyone is welcome to send a pull request to support maven or any other build tool, as long as it's reasonably in common use and not too exotic.
